language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/reg_num_tests

node_js:
  - "v9.11.2"

before_script:
  - psql -c 'create database  reg_num_tests;' -U postgres
  - psql -U postgres -d reg_num_tests -a -f tables.sql

after_success: npm run coverage

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2